name: CustomItemSystem
main: com.example.customitemsystem.CustomItemPlugin
version: 1.0
api-version: 1.20
commands:
  addability:
    description: Add an ability to the item in your hand.
    usage: /<command> <ability>
