name: CustomItemSystem
main: com.example.customitemsystem.CustomItemPlugin
version: 1.0
api-version: 1.20
commands:
  addability:
    description: Add an ability to the item in your hand.
    usage: /<command> <ability>
  slayer:
    description: Open the slayer menu
    usage: /<command>
  armor:
    description: Open the custom armor menu
    usage: /<command>
  ah:
    description: Open the auction house
    usage: /<command>
  ahsell:
    description: List the held item in the auction house
    usage: /<command>
